/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.frcteam2930.common;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
  // @Test void someLibraryMethodReturnsTrue() {
  //     Library classUnderTest = new Library();
  //     assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
  // }
}
